language: php
php:
  - 5.3
  - 5.4
env:
  global:
    - secure: "UAPyRnASwqjRuaurx5NUAzqGk9mEz9OECjN5ULw8qZ0tRFjO+bfHSiafvXiOICDNIcd+iRYHGoCaV/vJtgR9KyP7g1hGlWpBn+uQtCqgXUr/IkmDi2d5AX7I3KYHnUPB579V0F6AmsnvSKlZQBpZPL5z1sLRUQzgdpWgxXuvPSE="
    - secure: "WWra7m/UTKrEAL00FECUkclzXr4c0/LxJRA3fC5CXAhMhnxZtsDQJeFPefwlPrNTAqMejN64cxFzoOH6n1oAfDa8s1MFUBVmMxiI5Kkh7vvP4500a54BzIbLiBHyJt9JcRwnCj6DrKMWKqIYbsmWsq7QPiAXybyDO0UfUr+B0UM="
    - WL_DISABLE_SPARQL_UPDATE_QUERIES_BUFFERING=true
  matrix:
#    - WP_VERSION=latest
    - WP_VERSION=3.8.1  WP_MULTISITE=0
    - WP_VERSION=3.7.1  WP_MULTISITE=0
    - WP_VERSION=3.8.1  WP_MULTISITE=1
    - WP_VERSION=3.7.1  WP_MULTISITE=1
#    - WP_VERSION=3.8    WP_MULTISITE=0
#    - WP_VERSION=3.6.1  WP_MULTISITE=0
#    - WP_VERSION=3.5.2  WP_MULTISITE=0
#    - WP_VERSION=3.4.2  WP_MULTISITE=0
#    - WP_VERSION=3.3.3  WP_MULTISITE=0
#    - WP_VERSION=3.8    WP_MULTISITE=1
#    - WP_VERSION=3.7.1  WP_MULTISITE=1
#    - WP_VERSION=3.6.1  WP_MULTISITE=1
#    - WP_VERSION=3.5.2  WP_MULTISITE=1
#    - WP_VERSION=3.4.2  WP_MULTISITE=1
#    - WP_VERSION=3.3.3  WP_MULTISITE=1

before_install:
  - sudo apt-get -y -qq update
  - sudo apt-get -y -qq install curl libcurl3-gnutls libgnutls26

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit

notifications:
  slack: insideout10:NcslbQWVmD4YPInDq8TpBIno
